config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  root to: 'contacts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord  
  validates :first_name, :last_name, presence: true
  validates :telephone, presence: true, numericality: true, length: { minimum: 10, maximum: 10 }

  NUMBER_VALUE = {
    '2' => ['a', 'b', 'c'],
    '3' => ['d', 'e', 'f'],
    '4' => ['g', 'h', 'i'],
    '5' => ['j', 'k', 'l'],
    '6' => ['m', 'n', 'o'],
    '7' => ['p', 'q', 'r', 's'],
    '8' => ['t', 'u', 'v'],
    '9' => ['w', 'x', 'y', 'z']
  }

  def full_name
    first_name + ' ' + last_name
  end

  def self.get_combination(combination, next_digits)
    if next_digits == ""
      @output << combination
    else
      for letter in Contact::NUMBER_VALUE[next_digits[0]] do
        get_combination(combination + letter, next_digits[1..-1])
      end
    end
  end

  def self.number_word_combination(digits)
    @output = []
    if digits
      get_combination("", digits)
    end

    @output
  end

  def self.search(search_params)
    contacts = self.all
    return contacts if search_params.blank? || search_params[:user_number].blank?
    if search_params.present? && search_params[:user_number].present?
      contacts_search = contacts.where("contacts.telephone LIKE ? ", "%#{search_params[:user_number]}%")
      unless search_params[:user_number].include?('0') || search_params[:user_number].include?('1')
        letter_array = number_word_combination(search_params[:user_number])
        search_array = letter_array.map {|val| "%#{val}%" }
        name_search = contacts.where("contacts.first_name ILIKE ANY ( array[?] ) OR contacts.last_name ILIKE ANY ( array[?] )", search_array, search_array)
        contacts_search = (contacts_search + name_search).uniq
      end
    end
    contacts_search
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.search(params[:search])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to '/' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to '/' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :telephone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      next unless message.is_a? String
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} alert-dismissable", style: "margin: 10px;") do
        concat content_tag(:button, 'x', class: "close", style: "font-size: 18px;", data: { dismiss: 'alert' })
        concat content_tag(:p, message)
      end)
    end
    nil
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact_details.html.erb
<% if @contact.present? %>
  <div class="contact-detail">
    <hr>
    <div class="row">
      <div class="digit contact-name">
        <div class="sub">Showing Contact Detail</div>
      </div>
    </div>
    <div class="row">
      <div class="digit contact-name">
        First Name = <%= @contact.first_name %>
      </div>
    </div>
    <div class="row">
      <div class="digit contact-name">
        Last Name = <%= @contact.last_name %>
      </div>
    </div>
    <div class="row">
      <div class="digit contact-name">
        Telephone = <%= @contact.telephone %>
      </div>
    </div>
    <div class="row">
      <div class="digit contact-name">
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/_user_contacts.html.erb
<div class="row">
  <div class="digit contact-name">
    <div class="sub">Showing <%= @contacts.count %> contacts</div>
  </div>
</div>
<% @contacts.each do |contact| %>
  <div class="row">
    <div id="contact-<%= contact.id %>" class="digit contact-name" data-contact-id="<%= contact.id %>"><%= contact.full_name %>
      <i class="fa fa-angle-right" aria-hidden="true"></i>
      <div class="sub"><%= contact.telephone %></div>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="container">
  <div class="contacts-all">
    <%= render 'user_contacts' %>
  </div>
  <div class="user_contact">
    <%= render 'contact_details' %>
  </div>
  <div class="button close-contact">Close Contact</i></div>
  <%= form_tag 'contacts', id: 'contacts-form', method: :get, class: 'search', remote: true do %>
    <hr>
    <input id="output" type="text" name="search[user_number]" value="" class="form-control" readonly="readonly">
    <div class="row">
      <div class="digit number" id="one">1</div>
      <div class="digit number" id="two">2
        <div class="sub">ABC</div>
      </div>
      <div class="digit number" id="three">3
        <div class="sub">DEF</div>
      </div>
    </div>
    <div class="row">
      <div class="digit number" id="four">4
        <div class="sub">GHI</div>
      </div>
      <div class="digit number" id="five">5
        <div class="sub">JKL</div>
      </div>
      <div class="digit number">6
        <div class="sub">MNO</div>
      </div>
    </div>
    <div class="row">
      <div class="digit number">7
        <div class="sub">PQRS</div>
      </div>
      <div class="digit number">8
        <div class="sub">TUV</div>
      </div>
      <div class="digit number">9
        <div class="sub">WXYZ</div>
      </div>
    </div>
    <div class="row">
      <div class="dig">*
      </div>
      <div class="digit number">0
      </div>
      <div class="dig">#
      </div>
    </div>
    <div id="clear" class="button">Clear Number</i></div>
  <% end %>
</div>

<div class="modal fade" id="user-contact-modal" role="dialog" style="display: none;overflow-y: auto;"></div>

app/views/contacts/index.js.erb
$('.contacts-all').html("<%= j render 'user_contacts', locals: { contact: @contact } %>");

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @contact.telephone %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/show.js.erb
$('.user_contact').html("<%= j render partial: 'contact_details', contact: @contact %>");
$('.close-contact').show()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhoneContact</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row"> <%= flash_messages %></div>
    <%= yield %>
  </body>
</html>